# Category list of surfaces. Each category does not have "instance ID".
# Reference(TIER IV INTERNAL LINK): https://drive.google.com/file/d/132nKnXc7vq9Bjj0quoXDFGi9q5jtrXuY/view?usp=drive_link
- road
- sidewalk
- building
- wall_fence
- wall/fence
- pole
- vegetation_terrain
- vegetation/terrain
- sky
- road_paint_lane_solid_white
- road_paint_lane_dash_white
- snow
- road_paint_arrow
- road_paint_restricted_area
- road_paint_lane_deceleration
- road_paint_character
- road_paint_lane_stop_line
- road_paint_crosswalk
- road_paint_lane_dash_yellow